name: C++ CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Compiler
        run: |
          if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
            sudo apt-get update
            sudo apt-get install -y build-essential
            sudo apt-get install -y software-properties-common
            sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
            sudo apt-get update
            sudo apt-get install -y gcc-13 g++-13
            wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
            sudo apt-add-repository "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-17 main"
            sudo apt-get update
            sudo apt-get install -y clang-17
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            # Install GCC 13 on Windows (adjust based on availability)
            # Install Clang 17 on Windows (adjust based on availability)
            echo "Windows setup"
          elif [ "${{ matrix.os }}" = "macos-latest" ]; then
            # Install GCC 13 on MacOS (adjust based on availability)
            # Install Clang 17 on MacOS (adjust based on availability)
            echo "macOS setup"
          fi

      - name: Configure with CMake
        run: cmake -B build -S test

      - name: Build with CMake
        run: cmake --build build

      - name: Run tests
        run: ctest --test-dir build
