name: C++ CI

on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
 build:
  runs-on: ${{ matrix.os }}
  strategy:
    matrix:
      os: [ubuntu-latest, windows-latest, macos-latest]
      compiler: ['gcc', 'clang', 'msvc']
      
  steps:
  - uses: actions/checkout@v2
  - name: Configure with CMake
  - name: Setup C++ environment
    uses: actions/setup-cpp@v2
    with:
      cpp-version: latest
      
    run: cmake -B build -S test

  - name: Build with CMake
    run: cmake --build build

  - name: Run tests
    run: ctest --test-dir build
